// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceApi.Data;

#nullable disable

namespace ResourceApi.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260222034155_CreatePokemonTypeTable")]
    partial class CreatePokemonTypeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ResourceApi.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMythical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseExperience = 64,
                            Generation = 1,
                            Height = 0.7m,
                            ImageUrl = "bulbasaur.png",
                            IsLegendary = false,
                            IsMythical = false,
                            Name = "Bulbasaur",
                            PokedexNumber = 1,
                            Weight = 6.9m
                        },
                        new
                        {
                            Id = 4,
                            BaseExperience = 62,
                            Generation = 1,
                            Height = 0.6m,
                            ImageUrl = "charmander.png",
                            IsLegendary = false,
                            IsMythical = false,
                            Name = "Charmander",
                            PokedexNumber = 4,
                            Weight = 8.5m
                        });
                });

            modelBuilder.Entity("ResourceApi.Models.PokemonTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#F08030",
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#6890F0",
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#78C850",
                            Name = "Grass"
                        });
                });

            modelBuilder.Entity("ResourceApi.Models.PokemonTypeEntity", b =>
                {
                    b.HasOne("ResourceApi.Models.Pokemon", null)
                        .WithMany("Types")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("ResourceApi.Models.Pokemon", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
